name: taurouf_s_application9
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  google_sign_in: ^5.0.7
  outline_gradient_button: ^2.0.0+1
  flutter_svg_provider: ^1.0.3
  google_maps_flutter: ^2.0.0
  table_calendar: ^3.0.6
  intl: ^0.17.0
  fluttertoast: ^8.0.8
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Nexa Bold
      fonts: 
        - asset: assets/fonts/NexaBold.ttf
          weight: 700
    - family: Nexa
      fonts: 
        - asset: assets/fonts/NexaBook.ttf
          weight: 300
    - family: Nexa Light
      fonts: 
        - asset: assets/fonts/NexaLight.ttf
          weight: 400
